name: Frontend CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.11.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      API_URL: "https://api.monopoly.renswens.nl/api"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Change directory
        run: cd /home/monopoly/actions-runner/_work/levendmonopoly-frontend/levendmonopoly-frontend
      - run: pm2 restart 0
